######################################################################
#
#  File        :  user.action
#
#  Purpose     :  User-maintained actions file, see
#                 https://www.privoxy.org/user-manual/actions-file.html
#
#  Copyright   :  Written by and Copyright (C) 2002-2022 the
#                 Privoxy team. https://www.privoxy.org/
#
######################################################################

# This is the place to add your personal exceptions and additions to
# the general policies as defined in default.action. (Here they will be
# safe from updates to default.action.) Later defined actions always
# take precedence, so anything defined here should have the last word.

# See https://www.privoxy.org/user-manual/actions-file.html, or the
# comments in default.action, for an explanation of what an "action" is
# and what each action does.

# The examples included here either use bogus sites, or have the actual
# rules commented out (with the '#' character). Useful aliases are
# included in the top section as a convenience.

#############################################################################
# Aliases
#############################################################################
{{alias}}
#############################################################################
#
# You can define a short form for a list of permissions - e.g., instead
# of "-crunch-incoming-cookies -crunch-outgoing-cookies -filter -fast-redirects",
# you can just write "shop". This is called an alias.
#
# Currently, an alias can contain any character except space, tab, '=', '{'
# or '}'.
# But please use only 'a'-'z', '0'-'9', '+', and '-'.
#
# Alias names are not case sensitive.
#
# Aliases beginning with '+' or '-' may be used for system action names
# in future releases - so try to avoid alias names like this.  (e.g.
# "+crunch-all-cookies" below is not a good name)
#
# Aliases must be defined before they are used.
#
# These aliases just save typing later:
#
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

# These aliases define combinations of actions
# that are useful for certain types of sites:
#
fragile     = -block -crunch-all-cookies -filter -fast-redirects -hide-referer -prevent-compression
shop        = -crunch-all-cookies allow-popups

# Your favourite blend of filters:
#
myfilters   = +filter{html-annoyances} +filter{js-annoyances} +filter{all-popups}\
              +filter{webbugs} +filter{banners-by-size}

# Allow ads for selected useful free sites:
#
allow-ads   = -block -filter{banners-by-size} -filter{banners-by-link}
{-block \
}
wss://msg.olx.in/ws/chat
wss-mobile.slack.com
wss-backup.slack.com
wss-primary.slack.com
#... etc.  Customize to your heart's content.

## end aliases ########################################################
#######################################################################

# Begin examples: #####################################################

# Say you have accounts on some sites that you visit regularly, and you
# don't want to have to log in manually each time. So you'd like to allow
# persistent cookies for these sites. The allow-all-cookies alias defined
# above does exactly that, i.e. it disables crunching of cookies in any
# direction, and the processing of cookies to make them only temporary.
#
{ allow-all-cookies }
#.sourceforge.net
#sunsolve.sun.com
#slashdot.org
#.yahoo.com
#.msdn.microsoft.com
#.redhat.com

# Say the site where you do your homebanking needs to open popup
# windows, but you have chosen to kill popups uncoditionally by default.
# This will allow it for your-example-bank.com:
#
{ -filter{all-popups} }
.banking.example.com

# Some hosts and some file types you may not want to filter for
# various reasons:
#
{ -filter }

# Technical documentation is likely to contain strings that might
# erroneously get altered by the JavaScript-oriented filters:
#
#.tldp.org
#/(.*/)?selfhtml/

# And this stupid host sends streaming video with a wrong MIME type,
# so that Privoxy thinks it is getting HTML and starts filtering:
#
stupid-server.example.com/
{+block{Layered ads.} \
 +handle-as-empty-document \
}
.adshot.
.affimo.
.applieda.com
.google.ru
.livejasmin.
.livejasmincdn.
.mediaunder.
.undere.com
.warezlayer.
/js/ulayer.js
/libraries/jspopunder.min.js
jmobqzz.dnsalias.net

# Example of a simple "block" action. Say you've seen an ad on your
# favourite page on example.com that you want to get rid of. You have
# right-clicked the image, selected "copy image location" and pasted
# the URL below while removing the leading http://, into a { +block{reason} }
# section. Note that { +handle-as-image } need not be specified, since
# all URLs ending in .gif will be tagged as images by the general rules
# as set in default.action anyway:
#
{ +block{Nasty ads.} }
.0427d7.
.0llii0g6.
.1378km.de
.214234234234.info
.23mfdoe32rs.
.24smile.
.24start.me
.29bca6cb72a665c8.
.2cnt.net
.2l322.info
.2mdn.net
.32red.com
.33across.
.35l3.info
.35l7.info
.45i73jv6.
.4allclick.ru
.4fcams.
.5l37.info
.5l38.info
.5min.com
.600z.com/aj/*
.6angebot.
.777-partner.
.777partner.
.92l0.info
.99admanager.com
.9ts3tpia.com
.Bizographics.
.a-mo.
.a1.yimg.com
.aad73c550c.
.abendblatt.de/.*teaser
.abv.at
.acdcdn.g
.actionallocator.
.ad-balancer.
.ad-traffic.
.ad.netzquadrat.
.ad6media.
.adalizer.
.adap.tv
.adblade.
.adboost.
.adbooth.
.adbureau.
.adbutler.
.adcash.
.adcell.
.adcount.
.addcontrol.
.addthis.
.addynamo.
.adengage.
.adexprt.
.adform.
.adfux.
.adglamour.
.adhands.
.adition.
.adjames.
.adjug.
.adjuggler.
.adk2.
.adklick.
.adlink.
.adlink.net
.adme.de
.admediaking.
.admngronline.
.admoon.
.adorun.
.adperform.
.adpionier.
.adplans.
.adpushup.
.adquality.
.adranking.
.adrecover.
.adrevolver.
.adriver.
.adrolays.
.adroll.
.ads4finies.
.adsafeprotected.
.adsbyisocket.
.adscale.
.adsense.
.adshopping.
.adskape.ru
.adsmarket.
.adsniper.
.adspdbl.
.adsrvr.
.adtech.
.adtraxx.
.adtwothree.
.adultadworld.
.adultgulf.
.adultimate.
.adultpay.net
.adultshop.de
.adulttiz.com
.adulttubetraffic.
.adv.
.advancedadv.
.adverserve.
.advmaker.
.advolution.
.advombat.
.advpoints.
.advprotizer.
.adzerk.
.adzoe.
.adzonk.
.afcyhf.
.affarity.com
.affec.
.affili.
.affiliando.
.affiliatelounge.
.affinity.com
.afil.*.yahoo.com
.agentur-wagner.de
.ahcdns.com
.aleadpay.
.allfreegay.com
.allmt.com
.am10.ru
.am11.ru
.am15.net
.amazon-adsystem.
.amazonlive.
.ampproject.
.amung.us
.annienne.com
.anzeigen.abendblatt.de
.anzeigenlieferant.de
.apibuymedia.
.apicit.net
.apreces.
.aprement.
.apromoweb.com
.asnetworks.de
.asrety.com
.assoc-amazon.
.atdmt.com
.atlassolutions.
.atsfi.de
.au2m8.
.auto.de/offer/oneofferpromotion
.auxmoney-partnerprogramm.
.avatraffic.
.awempire.
.awltovhc.com
.awmpartners.
.axprod.net
.ba2b687.
.banner.t-online.de
.bannerhost.
.batilo.
.baynote.net
.baypops.com
.belboon.de
.berlinermedienvertrieb.
.best-pagerank.
.bestevernews.com
.besthitsnow.
.bet365.
.betaffs.
.betarget.
.betclick.
.bfd69dd9.
.biallo1.de
.bidswitch.
.bidsystem.com
.bidvertiser.
.bigpoint.com
.bild.de/(.*/)partner/
.bild.de/(.*/)shop/
.bild.de/.*/koso/(.*/)
.bild.de/fotos/.*390x125
.bin-layer.
.binlayer.
.binmedia.ru
.bistr4.ru
.blogads.
.blueadvertise.
.bluecava.
.blumi.to
.bodyclick.
.bon-kredit.
.bongacams.
.bongacash.
.boostduplicate.info
.bornpay.
.briedenredaktion.de
.broils.ru
.browser-update-meldung.
.brqvld0p.
.btv.at
.c-col.com
.c-planet.net
.cam4.
.campartner.
.cams.com
.carveac.com
.casalemedia.
.cash-flow-international.
.cash4movie.
.cdapmsfour.
.cdapmsone.
.cdapmssix.
.cdapmsthree.
.cdxndirectopt.
.cdxnn.
.cdxnopt.
.cedexis.
.chaturbate.
.cheatbeat.
.checkout-proxy.info
.ciement.com
.circules.com
.clickintext.
.clickpapa.
.clicksvenue.
.clicksz.
.clickunder.
.clixgalore.
.cloakac.com
.cltomedia.info
.code-proxy.info
.codeproject.com/script/Adm/*
.collective-media.
.commindo-media-ressourcen.
.conduit-banners.
.connexionsecure.
.contact-direct.ru
.contaxe.com
.content.ad
.contextmatters.
.contextual.
.coolmirage.com
.countomat.com
.criteo.com
.criteo.net
.crowdgravity.com
.crowdscience.
.crwdcntrl.
.cumeron.
.cuonemove.info
.customer-support24.
.cxense.
.d03x2011.
.dadegid.ru
.dafficha.
.daisycon.com
.daredac.
.datefree.
.datingadzone.
.dditservices.com
.dealtime.
.decknetwork.
.demandbase.
.deplayer.net
.dircash-promost.
.directrev.
.domainprofi.
.domainsponsor.
.donaar.de
.dosugcz.
.doubleclick.
.doublepimp.com
.doublerecall.com
.dpbolvw.net
.drowle.com
.drss.tv
.ds1.nl
.dsultra.
.dt07.net
.dvd-verleih.info
.dynamic-advertising.
.dynamicyield.
.e-lationshop.
.eads.
.ebayobjects.com
.ebuzzing.
.ebuzzingvideo.
.ebz.io
.econa.
.econda-monitor.
.edelight.biz
.ee74ff81b44.
.efficienttraffic.
.effiliation.
.efoodsdirect.
.egooad.
.ektezis.ru
.eloqua.
.en25.com
.enfingratuit.
.enoratraffic.
.enquisite.com
.ero-advertising.
.erovation.com
.estiques.
.etology.com
.etoro.
.eurogrand.
.exad.me
.exchangecash.de
.exelator.
.exhost1.me
.exoclick.
.extra33.com
.fairfax.com.au
.fairlink.ru
.fapturbo.
.fastclick.
.fastpic./.*\.swf
.fastpromo.in
.faxso.ru
.feedjit.
.fetchback.com
.filefactory./img/premium/
.filepost.com/static/images/bn/
.filetarget.
.financeads.
.finanzen.net/swf/a_anzeige/
.findmyhome.at/format
.finya.de/shop/
.firstlightera.
.firstload.de/affiliate/*
.flashmediaportal.com
.flashtalking.
.fleshlight-international.
.fleshlight.
.fleshlightstore.
.flipflapflo.
.fmpub.net
.fncash.
.forex*.com/affiliates/
.forum-maximus./.*\.swf
.fpctraffic2.
.friendlyduck.com
.friendscout24./msnquardusercsl.html
.ftd./gujAd/gujAd.js
.ftjcfx.com
.fullcirclestudies.
.fulltiltpoker.
.fundingchoicesmessages.google.com
.funpic.de/layer.php
.gagacon.com
.gameoftraffic.
.games724.
.gamesaktuell.de/bcommon/swf/
.gateway-03.com
.gaypicturepost.com
.generic4all.
.getfplayer.com
.getfreebacklinks.
.getfreebl.com
.getresponse.com
.gfhdkse.com
.glam./.*\.swf
.glplanet.me
.go2jump.org
.go2speed.org
.godaddy.
.gogousenet.com
.goklics.
.gokliks.
.good-teaser.info
.google-analytics.
.googleadservices.
.googlesyndication.
.googletagmanager.
.gorillanation.
.gpr.hu
.gravity.com
.grifiins.ru
.gsadserver.
.gumgum.
.gunggo.com
.guruads.
.guruplay.
.gutscheine.stern.de
.hash-traff.
.havetohave.com
.hearstnp.com
.heise.de/avw-bin/ivw/
.heise.de/imgs/.*336x200
.heise.de/ivw-bin/ivw/
.hellobar.com
.hifitest.de/ht_werbebanner
.high-tra-ff.
.hightraonlineff.
.highwebmedia.
.hit.ua
.hklu.info
.hopfeed.
.hubrus.
.hyperlinksecure.com
.i12.de
.ibario.com
.ibillboard.
.iclive.com
.iconist.de
.icqadvvk.com
.id5-sync.
.iftraff105.
.iftraff107.
.ikersont.com
.im-tub.
.im1-tub.
.im2-tub.
.im3-tub.
.im4-tub.
.im5-tub.
.im6-tub.
.imagans.
.imagevenue.com/interstitial.rotate1.js
.imgbabes./(splash|script).php
.imgnip.com/.*\.swf
.imgshots.com/ad.html
.imlive.
.impact-ad.
.impromot.
.imshopping.
.ind.br
.indextools.com
.individuad.
.inferalton.
.influads.
.infolinks.
.infowars./.*/x/
.inteliad.
.intensifier.
.intercasino.
.intergi.
.intimetra.
.intimshop.ru
.investingchannel.
.invitemedia.com
.ioam.
.ioiiioi.info
.is-very-good.org
.isonlynews.net
.iss-xund.eu/2012/
.itam-gmbh.com/astracker
.ivwbox.
.jadedi.com
.jasmin.com
.javbucks.
.jdoqocy.com
.jetswap.com
.jivosite.
.jsdelivr.
.juicyads.com
.jujzh9va.
.kalooga.
.kampyle.
.kaufda.
.kaufda.de
.kaufdown.de
.key-sign.
.kingtraf.
.kitcode.
.kliklink.
.knowone.de/(.*/).*\.(swf)$
.koliser.com
.kolites.
.koluty.
.komdat.com
.koramgame.com
.kqzyfj.com
.krutilka.net
.kundwerk.de
.lablue.de/js/adLink*.js
.lacemme.com
.layer-ad.
.layermedia-adserver.
.leadformix.
.lesen.to/layer/
.lifepromo.biz
.lifestatic.biz
.liftsk.
.ligatus.
.lijit.com
.linkbucks.com/.....aad/
.linkbucksmedia.com/director/
.linkcollider.
.linkstorm.net
.livekeywestmusic.com
.liverail.
.livetraf.
.loading-delivery1.
.loneday.
.loomia.com
.lotto24.de
.love-sms.tv
.luckyorange.com
.luxup.ru
.m57ku6sm.
.mabirol.com
.managermest.ru
.marketing-by-phone.
.marktorakel.com/.*\.swf
.maxi-ad.
.maxymiser.
.media-ks.
.mediaip.ru
.medialand.ru
.mediaplex.
.mediatarget.
.meendocash.
.megamixgroup.
.megastock.
.mehrwertdienstekompetenz.de
.meinprospekt.de
.mestreafiliados.
.metaboli.
.mezima.com
.mgid.com
.mirago.co.uk
.mirago.com
.mirando.de
.ml314.
.mlno6.
.mmaaxx.
.mmoga.com
.mobbober.com
.mobidump.com
.moijs.
.mokonocdn.com
.morehitserver.
.morenews3.
.moreusers.info
.morevisits.info
.mp-success.com
.mpnrs.com
.mpros.de
.my-dirty-hobby.
.my-layer.net
.my-proads.
.mydeluxegames.com
.mydirtyhobby.com
.mydownloader.
.mypagerank.
.mytizer.
.mytrannycams.
.mywebclick.net
.naiadsystems.
.nashevideo.info
.nativeads.
.ncjshop.co.uk
.ndtv.com/bookflip/
.neosmi.ru
.netagent.cz
.netdebit-counter.
.network-media.
.netxmedia.net
.new-promo2012.
.new-tizer.com
.news.at/prod/.*swf
.news.at/prod/partner
.nimblecommerce.com
.nmcdn.us
.nonstoppartner.
.nrelate.
.nugg.ad
.nuggad.net
.numberium.
.oclaserver.
.odnoklassniki.ru
.offerandreview.
.okeo.ru
.okoshechka.net
.olizyr.com
.onadadserver.
.onadmarketing.
.onatrack.
.onclickads.
.online-media24.
.openx.net
.openx.org
.optimost.
.otmsrv.com
.ourbesthits.
.ovskin.ru
.pagerankturbo.
.pagesinxt.com
.partnercash.
.partnerearning.
.partnermax.
.partypoker.com
.pay4mobile.
.paymonsters.
.pazoo.com/pazoo-tv/
.pcgames./.*.swf
.peer39.net
.peoplesearchaffiliates.
.perfectaudience.
.pgmediaserve.com
.picbucks.com/track/
.pinkvisualgames.
.piroji.
.pixfuture.
.pixhost.org/image/rotate/
.placement24.
.planet49.com
.planetapes.de
.plista.com
.plugrush.
.pluso.ru
.po.st
.pokersemdeposito.
.poolk.
.pop-bazar.net
.popads.
.popclick.net
.poponclick.
.popunder.
.popunderz.
.porndad.
.ppro.de
.preisomat.eu
.premiumcpm.
.premiumpromotions.
.privatamateure.com/promotion/
.privatewebseiten.com
.profitstat.
.profiwin.de
.profstat.
.promedia-click.ru
.promo4partners.
.promocionesweb.
.promoloader.com
.promosrv.com
.propagandafront./.*\.swf
.propellerads.
.propellerpops.
.protizer.
.protrafv2.
.proximic.com
.proxysolutions.net/affiliates/
.prtrackings.
.ptp24.com
.pub2srv.
.pubexchange.
.publisher.to
.pubmatic.
.pussycash.
.putags.com
.pz-news.de/cms_media/module_wb/
.q1xyxm89.
.qnsr.com
.quisma.com
.qwobl.net
.r7e0zhv8.
.rankmonkey.
.reachjunction.
.realdatechat.
.realfreedate.
.realityclick.
.redmoonstudios.de/affiliate/*
.redtram.
.refinedads.
.relatedweboffers.
.relink.us/swf/
.research.de.com
.retargetpro.
.returso.
.rghost.ru
.rlcontrol.
.rmbn.
.robocat.me
.rocketfuelinc.
.rocketfuelinc.com
.rtbidder.net
.rtcorr.
.rubiconproject.
.ruclicks.
.rulerclick.
.runetki.com
.ruscams.
.russianamerica.
.s3exy.com/n..gif
.sancdn.net
.sascentral.com
.sceno.
.schnell400euro.
.secure-clicks.
.selsin.net
.seoz.info
.serious-cash.
.serving-sys.
.serving-sys.com
.sexad.net
.sexmoney.
.sexpartnerx.
.sextizer.net
.sexuria.com/layer*
.sexypower.
.shareasale.
.sharefoco.com
.shop.tc/
.shop4adomain.com
.shoplove.
.shortnews.de/.*\.swf
.sixsigmatraffic.
.slimspots.
.slimtrade.
.smartadcheck.
.smartadserver.
.smartbn.ru
.smartredirect.
.smi2.ru
.smiletraf.
.smsdate.com
.sochetat.net
.soft4dle.com
.sonobi.
.sparkstudios.
.spotrails.com/ca.php
.spox.
.srvad.
.stableprofit4you.
.stargames.
.stayeda.com
.streamate.
.streamateaccess.
.streamray.com/
.su01.ru
.subscriberconcierge.com
.sunmaker.
.sunnysales.biz
.super-adv.
.sw3m5ncmn.
.sweed.to
.t-online.de/-/id_68029888
.t9media.
.taboola.
.taboolasyndication.
.tafyeta.ru
.tagol2.ru
.targetingnow.
.tbn.ru
.tdstraff.ru
.teasermedia.
.teasernet.
.teaservizio.
.technik-test.biz
.telefoncash.
.telemetryverification.
.textbacklinkexchanges.
.tfag.de
.the-adexchange.
.theadex.
.thefilter.com
.thehitsusa.
.theplatform.com
.thumbshots.
.tinsvt.ru
.tipico.
.tisapama.
.tizer-click.
.tizer6.net
.tizerfly.net
.tizergun.
.tizermine.
.tizerplatform.
.tizerset.
.tkqlhce.com
.tldadserv.com
.tlvmedia.
.tmserver-1.
.tmserver-2.
.topeuro.
.topstuds.com
.tqlkg.com
.trackvoluum.
.tradedoubler.
.tradetracker.
.traffget.
.traffic-network.
.traffic.ru
.trafficfacts.
.trafficforce.
.trafficgally.
.trafficholder.
.trafficmanager.net
.trafficmaxx.
.trafficrevenue.
.trafficshop.
.trafficundercontrol.com
.trafficvending.
.traffmedia.
.traffpay.
.traffshop.
.traffstock.
.trafftrade.
.trafgun.
.trafinfo.
.trafovik.ru
.trafsiz.
.trafstock-in.
.traient.
.trakio1.net
.tremormedia.
.trigami.com
.trw12.com
.turn.com
.tv2n.net
.tvbutler.at/mediafiles/.*swf
.twilightparadox.com
.twinplan.
.tynt.
.uimserv.net
.under-click.
.usemax.de
.usermediaclick.
.utarget.co.uk
.v2mlred.
.vdo.
.veeseo.
.verticalacuity.com
.verticalnetwork.
.vertoz.
.vghd.com
.vgwort.de
.videogameszone./.*\.swf
.videosz.com
.vidible.tv/prod/tags/
.vidustal.com
.viglink.
.vimgs.ru
.vip-click.info
.vip-traff.
.vipaccess.info
.viragemedia.com
.visit-x.net/promo/
.visitweb.com
.visualwebsiteoptimizer.
.vk.com
.vod-cash.com
.voicefive.com
.vuukle.
.w3server.eu
.wai.de
.warthunder.ru
.watchever.
.webclickmanager.
.webmasterplan.
.websale.
.webteaser.
.webtradecenter.
.webtrekk.
.welt./multimedia/archive/.*/*328x119*
.welt./sightloader_frame.*
.werbebooster.
.wigetmedia.
.wintotal.de/images/grafikfremd/*
.winwithoption.
.wiredminds.de
.wizard-traffic.
.worldbestcasinosistems.
.worldsoft-cms.info
.wpclktls.
.wt-rotator.
.wt-rotator105.ru
.wt-rotator111.ru
.wt-rotator19.
.wunderloop.net
.www-promo.de
.wwwpromoter.
.wz-rotator2.
.x19network.
.xaogi.
.xapads.com
.xcams.com
.xcasino.
.xclicks.net
.xdrrok.com
.xfuckbook.com
.xpartner.
.xwell.ru
.xx00.info
.xxxblackbook.
.yadro.
.yesmessenger.
.youradexchange.
.yourlayer.
.youtube./api/stats/
.zanox-affiliate.
.zanox.
.zarry.biz
.zergnet.com
.zinzimo.info
.zxxds.net
/(.*/)adhandler/
/(.*/)partnerads.*.js
/(adsense|ads|adroot|adproxy|adkit|ad_jnaught|affiliate|footerads)/
/(aff|adx|scrollad).php
/.*filesonic.gif
/.*googleads.*.js
/.*parship.*.jpg
/.adserv/
/FloatingAd.*.js
/Images/reklama..gif
/MetaAdServer/
/Werbebanner/
/ad.html
/adGallery.html
/adReload.html
/adsid/
/ajax/ligatus/*
/banner/.*\.swf
/client/overture.aspx
/clientscript/affiliate.js
/cms_media/module_adbanner/
/container.html
/cxo_adtech/
/displayads/
/extjs/smartad.*\.js
/gfx/layer/*
/gujAd/
/images/banners/
/interstitial.wind.js
/interstitial_18plus.js
/js/(adcontrol|adframe|selfad|omsv_adau).js
/layer/layer.php
/module/Controller_Module_Community_SearchAd
/modules/common/sponsored_links_json.php
/newad/www/delivery/
/openx/
/premiumdownload.png
/rotator/
/share/www/delivery/
/special_ads/
/vtrack/
/wp-adv/
/wp-srv/ad/
/www/delivery/
/zanox/*
1g234kj23h4.info
1l32hj4ll11.info
1oiuyoiup.info
207.net
213.174.132.50
2352356234.info
247realmedia.com
2mdn.net
2o7.net
33across.com
3cnce854.com
46.165.197.231
4lucysu.com
5licosy.com
62.146.71.2/beta/web/swf/PushupClient.swf
62.212.73.194
85.17.73.67
a.lakequincy.com
a.partner-versicherung.de
a3.swp.de
abmr.net
acoda.net
adblade.com
adbrite.com
adbureau.net
adchemy.com
addthis.com
addthisedge.com
adlog.com.com
admeld.com
admob.com
adsense.com
adsense.google.com
adserver.freenet.
adservice.google.ca
adservice.google.co.in
adservice.google.co.kr
adservice.google.co.uk
adservice.google.co.za
adservice.google.com
adservice.google.com.ar
adservice.google.com.au
adservice.google.com.br
adservice.google.com.co
adservice.google.com.gt
adservice.google.com.mx
adservice.google.com.pe
adservice.google.com.ph
adservice.google.com.pk
adservice.google.com.tr
adservice.google.com.tw
adservice.google.com.vn
adservice.google.de
adservice.google.dk
adservice.google.es
adservice.google.fr
adservice.google.nl
adservice.google.no
adservice.google.pl
adservice.google.ru
adservice.google.vg
adsonar.com
adtech.panthercustomer.com
advertising.com
affiliate.chefgourmet.de
affiliates.a2hosting.com
afy11.net
ahherwebcams.
alert.scansafe.net/alert/.*
app-measurement.com
aquantive.com
atdmt.com
atwola.com
autocontext.begun.ru
banquant.com
beratersuche.rp-online.
beratersuche.welt.de
best.filmulet.ru
billabong3.wetter.
bodyc.biz
cdn.nsimg.net
cds2.freenet.
channelintelligence.com
chie8oo.com
clicks.runews.radeant.
clme.biz
clunder.net
cmcore.com
codata.ru
comm.kino.to
contactsin.mobi
contactsin.ru
coremetrics.com
crackac.com
creative.ak.fbcdn.net
crowdscience.com
d1110e4.se
dai.google.com
decdna.net
decideinteractive.com
depositfiles.com/payment_bornpayeu_subscribe.php
divertura.
doubleclick.com
doubleclick.com
doubleclick.net
doubleclick.net
doubleclickbygoogle.com
dvasub.kipfilms.ru
dw.com.com
dynamic1.dailytech.
eas.apm.emediate.eu
einkaufswelt.t-online.
erotraf.com
esomniture.com
extranet.leserauktion.de
fdata.over-blog.net/.*SocialPopin.js
files.bannersnack.net
fimserve.com
flingwebads.com
foxnetworks.com
freshnews.su
funny-sexxy.ru
g234kj23h4.info
golfclub.welt.de
google-analytics.com
googleadservices.com
googleadservices.com
googlesyndication-cn.com
googlesyndication.com
googlesyndication.com
googletagservices.com
gpt.js
gravity.com
gredinatib.
gstaticadssl.l.google.com
gutscheine.focus.de
gzhls.at/btn/
hiddenjs.ru
hitbox.com
hosting.lockhosts.com
htredir.com
icqadvnew.com
id.google.*/verify/*
iftraff100.ru
imagepix.org/Images/image112.gif
images.derstandard.at/.*.swf
img.kwick.de/banners/
imghoney.com/.*swf
imgpaying./18plus.htm
imiclk.com
imrworldwide.com
insightexpress.com
insightexpressai.com
intellitxt.com
invitemedia.com
ja.focus.de
join.boobfrog.com
kikiskska.ru
kka.agitos.de/
kka.idg.de
klonedaset.org
koreniztreh.net
lapeduzis.org
last.endplace.info
leadback.com
life.imagepix.org
lindwd.net
linuxundich./static/gigahosting.*
loadmovie.ru
lydiz.com
makeyourblog.biz
mediaclickru.
mediadsale.ru
medianaft.ru
mobiledirectors.com
mobirollcom.ru
mookie1.com
motionhits.com
mpmcash.com
myads.com
negolist.com
netconversions.com
neuwagen.bild.
neuwagen.welt.de
new.boobfrog.com
nexac.com
nextaction.net
nexus.ensighten.com
nfm-adserver.de
nielsen-online.com
notifier.avira.com
nturveev.com
nudehall.com
numking.com
nummobile.com
o0.winfuture.de
offermatica.com
offers-service.*.
om.dsl.1und1.
omniture.com
omtrdc.net
openunder.net
openx-farm.ipxmuc-a.cxo.name
openx.*.
ordenn.ucoz.ru
ox.comventure.de
pap.ultramegabit.com
passul.t-online.
pay-hit.com
pic2profit.com/img/putanap/
pic2profit.com/ppb.php
pic4you.ru/rightdown/
pic5you.ru/rightdown/
picoasis.net/akoxxlayer.htm
picp2.com/img/putanap/
piwik1.datamints.com
pm14.com
postview.c-and-a.com
promo.awempire.
promo.javhd.com
promos.fling.com
qmebelist.ru
quantcast.com
quantserve.com
rcm-de.amazon.de
realmedia.com
revsci.net
rightmedia.com
rmxads.com
rotate.infowars.
rotation.linuxnewmedia.
ru4.com
rubiconproject.com
s0-2mdn-net.l.google.com
samsungadhub.com
sandugach.ucoz.ru
scorecardresearch.com
sd.lyc.btt.betarget.de
serv.markets.com/promo
sfileserver.glam.
sharethis.com
shopthetv.com
sincdn.appspot.com/img/(Profi|exali)/
slivdomen.ru
sof32dsso.ru
static.fastpic.ru/rift
static.lycos-europe.net/lea/
staticpix.spin.de/bn/
staticpix.spin.de/bn/cmedia/
stats.t-online.de/include-regionales-geo-targeting-js
stats.welt.de
subscribe.hearstmags.com
targetingmarketplace.com
themig.com
tr.de.adlink.net
traf-3rs.com
traf-monster.ru
trafers.ru
trapasol.
treetool.chip.de
trendnetcloud.com
turbobit.net/oexktl
usercode2.info
v2mlblue.org
versicherung.welt.de
vsexshop.ru
webmaster.pornme.com
wedinin.com
wmip.ru
wpteasertag.nzz.ch
ws.amazon.de
www.ccproxy.info
www.down1oads.com
www.enjoyops.de/chat.*
www2.glam.
www35.glam.
www8.glam.
xltraff.net
yieldmanager.com
yieldmanager.net
yldmgrimg.net
youknowbest.com
yumenetworks.com

{ +block{Ranklists} }
.cyonix.to
.desire-xx.net
.star-toplist.com
.xxx-hitz.org
.xxx-ranking.net
ranklist.us
.desire-xxx.net




{ +block{Microsoft Network} }
msnvidweb.vo.msecnd.net
vms.msn.com
estj.msn.com
#.catalog.video.msn.com
#db3.stj.s-msn.com
.s-msn.com/.*track.*
#weltderwunder.de.msn.com
db3.stb.s-msn.com/i/CB/.*.swf
db3.stb.s-msn.com/i/68/.*.swf
db2.stb.s-msn.com/i/C0/.*.swf
.101m3.com
c.microsoft.com/trans_pixel.aspx
g.msn.com/_0DEHP/
watson.telemetry.microsoft.com



{ +block{Gold&Silber Banner} }
#.marktorakel./index_files/gold_468x60.gif
.anlagegold24.de/img/.*x.*
.banner.rheingoldregio.
.bm-edelmetalle./frames/.*php
.bm-edelmetalle./frames/346x75.*.jpg
.bm-edelmetalle./frames/pf_.*.jpg
.gold-silber-anlage.de/images/GSA.gif
.gold.de/images/link_zu_uns/
.goldankauf123.
.goldmoney.com/banners/
.hartgeld.com/filesadmin/images/wb/
.imgcafe.com/view/uploads/banner.*
.kopp-verlag.de/\$WS/
.marktorakel./index_files/.*banner
.marktorakel./index_files/(gold-rush|dr-erhart|trader|standard460x65)
.marktorakel./index_files/silber-gold-verkauf-de.gif
.nice-servers./unser-finanzsystem/images/custom/.*.gif
.silber-gold-verkauf.de/resources/SGV.*
.silverbearcafe./.*banner.*
.silverbearcafe./.*berkey.*
.silverbearcafe./.*bullionbulls.*
.silverbearcafe./.*readymade.*
.survival-scout.at
.uploaded.to/img/public/i728x90.jpg
.zeitgeist-online.de/images/wbadvert/
/.*/gold_468x60.gif
/.*/krisenwelt312x91.gif
/.*/krivor180x225.gif
/.*wp-content/.*/.*banner.*.gif
/.*wp-content/.*/sgv-banner.*.gif
/.*wp-content/.*/spv310x91.gif
/.*wp-content/.*SMHAG.gif
/Transparek.gif
/images/alles-aus-einer-hand-proaurum.gif
/images/stories/hgb_01.gif
/krisenfee_logo.gif
/proaurum.*.gif
/rm_banner.gif
/wp-content/.*/Taurus2.jpg
/wp-content/.*/banner
/wp-content/.*/fairbanks2.jpg
/wp-content/.*/spannbauer.gif
/wp-content/uploads/.*180x200.*
/wp-content/uploads/.*300x250.*
/wp-content/uploads/.*_180x250.gif
/wp-content/uploads/2011/06/Kapitalschutz.gif
/wp-content/uploads/2012/08/01_125x105a_02.gif
/wp-content/uploads/.*180x400.swf
/wp-content/uploads/.*taurus_banner.jpg
www.krisenfrei.de/mh-logo.jpg
zeitenwende24.de/web/partner/
/art4u_banner468x60.jpg
/wp-content/uploads/2012/12/sw_3.gif


{ +block{Twitter, Facebook & Paypal} }
#.over-blog.
.facebook.com/common/scribe_endpoint.php
.facebook.com/dialog/oauth
.facebook.com/login/plugin_roadblock.php
.facebook.com/plugins/activity.php
.facebook.com/plugins/facepile.php
.facebook.com/plugins/fan.php
.facebook.com/plugins/like.php
.facebook.com/plugins/likebox.php
.facebook.com/plugins/recommendations_bar
.facebook.com/plugins/share_button.php
.facebook.com/widgets/like.php
.kachingle.com
.meebo.com
.meebocdn.net
.paypalobjects.com
.socialmediatabs.
.twing.
.twitter.
.wibiya.  #nerviger toolbar
api.tweetmeme.com
apis.google.com
connect.facebook.net
error.facebook.com
vk.com/widget_like.php
widgets.twimg.com



{ +block{Tracker} }
#stats.*.
.*.de/ivw/*
.33across.
.abmr.net
.active-tracking.
.addfreestats.
.admeld.
.adnxs.com
.adobetag.
.amazonaws.com/partner.gif
.analytics.brightedge.com
.analytics.edgekey.net
.analytics.edgesuite.
.analytics.yahoo.
.auto-ping.
.avira-analytics.
.beliebtestewebseite.de/0pixel.php
.betrad.
.blogtraffic.de/track
.btrll.com
.chartbeat.
.clickdensity.
.clicktale.
.clickzs.
.clickzzs.
.clustrmaps.
.comodoca.
.counterserver.
.cqcounter.
.customer.io
.cxo.name
.cya1t.net
.demdex.
.digidip.
.directtrack.
.dmtracker.
.e-referrer.
.effectivemeasure.
.eisenstein.dk
.etracker.
.ezakus.net
.fhserve.
.flagcounter.
.followistic.
.fruitflan.com
.galleries.bz/track/
.gaug.es
.gemius.
.gmodules.com
.googletagservices.
.googleusercontent.com/gadgets
.googleusercontent.com/ps/
.googleusercontent.com/tracker/*
.gosquared.com
.gostats.
.highfi-stats.
.histats.
.host-tracker.
.hypertracker.
.ic-live.
.ipcounter.
.ipv6-exp.l.google.com
.kissmetrics.
.krxd.net
.letitbit.net/counter/
.linkbucks./track
.linkedin.com/analytics
.linkedin.com/countserv
.linkedin.com/cws/share-count
.m-pathy.
.mathtag.
.media6degrees.
.meetrics.
.metric.gstatic.com
.mixpanel.com
.mookie1.
.mxcdn.net
.n-tv.de/stat/
.neostat.net
.netbiscuits.
.netclickstats.
.newrelic.
.newstogram.
.oewabox.at
.online-metrix.net
.openstat.
.optimizely.com
.ourstats.
.outbrain.com
.pardot.com
.parsely.com
.perfectmarket.
.pingdom.net
.polldaddy.
.postaffiliatepro.
.prchecker.info
.prfct.co
.pro-market.net
.profistats.
.prosieben./secure-static/
.qsstats.
.qualtrics.
.questionmarket.com
.raasnet.
.radarurl.
.research.de.com
.revolvermaps.
.ritecounter.
.salesforceliveagent.com
.scanscout.
.scootloor.
.scorecardresearch.
.sensic.net
.sharedcount.com
.sitestat.
.sitetag.
.skimresources.com
.srvntrk.
.statistics.
.stumbleupon.com/hostedbadge.php
.sublimevideo./_.gif
.sueddeutsche.de/l.gif
.szstats.
.t-online.de/cc-adcheck-js
.tape.tv/js/adblockdetection.js
.tapstream.
.tawas.de/
.tcimg.com
.tidaltv.com
.tns-counter.
.topix./t6track/
.trackalyzer.
.tracking101.
.tracking286.
.tracking887.
.trendcounter.
.trgt.eu
.tscapeplay.
.twyn.com
.unica.com
.urban-media.
.vdna-assets.
.veeseo.com/tracking
.videoplaza.tv/proxy/tracker
.vinsight.de
.visiblemeasures.
.visualdna.
.visualrevenue.com
.vmm-satellite1.com
.w55c.net
.waudit.
.websitesampling.
.webstats4u.
.welt.de/rem-.*/track/
.wemfbox.ch
.wipe.de
.wmtrackinglink.
.woopra-ns.com
.woopra.
.wwwstatistics.
.xing-share.
.yandex.ru
.youtube.com/ptracking/
.ytimg.com/yts/img/pixel-.*
.zeit.de/static/flash/brightcove/ZeitPixel.swf
.zieltracker.de
/(.*/)webtrekk.*.js
/(.*/)webtrekk.swf
/(meter|meter-echo|tracker|analytics).js
/.*/(track|tracking|_tracker|TrackingSystem|generictracking|ivw-faz.net|omnitracking|vInsight|adlib)\.js
/.*/GA.swf
/.*/analytics/(webtrends|EventTracker).js
/.*/js/webtrends.js
/.*GoogleAnalytics.(swf|js)
/.*IVWAnalytics.swf
/.*IVWTracker.swf
/.*find_related_dynamic.swf
/.*oas_analytics.js
/.*webtrekk_v1-3.swf
/_oobimg.php
/analysis-logger/
/analytics/tracker
/assets/inc/adblockerzaehlung
/cgi-bin/ivw/
/iam_toi.js
/js/tracking/
/log/webtracker
/logger/p.gif
/php-bin/functions/ivwbox/
/piwik.js
/ptracking/
/revenue-js/
/scripts/(tracker|track).js
/stats/Logger
/supportchat/(pixel|button).php
/track/
/tracker.(log|php)
/tracker.gif
/tvtotal/includes/php/tracking/stats.php
/vtrack/
204st.us
a2a.lockerz.
abakus.freenet.
ac.berliner-kurier.de
analytics.*.
apis.google.com/js/plusone.js
asset.userfly.
atracktive.
b.myspace.com
beacon-1.newrelic.
beacon.securestudies.com
beriche.ru
boss.berlinonline.de
botd.wordpress.com
botd2.wordpress.com
c.spiegel.de
cc.zeit.de
com.econa.com
csi.gstatic.com
doug1izaerwt3.cloudfront.net
entry-stats.huffpost.
geolocation.t-online.
goku.brightcove.com/1pix.gif
hit.gemius.pl
hits.informer.com
live01.ec2.cxo.name
livepass.conviva.com
livestat.derstandard.
log.pinterest.com
log.worldsoft-cms.info
lognormal.net
metrics.brightcove.
mm.welt.de/meter.js
npi.focus.de/cgi-bin/pagedot.gif
omni.focus.de
p.typekit.net/p.gif
partners-api.pinterest.com/v1/urls/count.json
pixel.redditmedia.com
plus.google.
plusone.google.
pulse-analytics-beacon.reutersmedia.net
r.chip.de/images/pic.gif
rem-track.bild.de
rl.heise.de/images/pic.gif
s.fs.t-online.de/js.gif
somni.focus.de
stat.aldi.
stats.11media.net
stats.adobe.
stats.easystores.
stats.globalgameport.com
stats.t-online.de/ati-js/
stats.tradekey.com
stats.vertriebsassistent.de
stats.wordpress.com
tags.bluekai.com/site/
tipi.api.t-online.de
track.ft.com
track.gawker.com
track.netshelter.net
tracker.*.
traf.visit-x.net
traffic.brand-wall.net
webtrendsanalytics.
widgets.pinterest.com/v3/pidgets/log/


{ +block{domain parking} }
.cpxinteractive.com
.debtowedzz.
.drugstoreschool.
.findultimatehealth.
.newhealthclinic.
.sedo.com
.urlquickfind.
.searchremagnified.com
.dsparking.
.nuseek.com
.parkingpremium.
/domainads/


{ +block{Test} }
st.chatango.com


{ -block }
.jamendo.com
.date-click.de
.adtmag.com
adressbuch.web.de


{ +fast-redirects{check-decoded-url} }

www.example.com/nasty-ads/sponsor.gif

# The URLs of dynamically generated banners, especially from large banner
# farms, often don't use the well-known image file name extensions, which
# makes it impossible for Privoxy to guess the file type just by looking
# at the URL.
# You can use the +block-as-image alias defined above for these cases.
# Note that objects which match this rule but then turn out NOT to be an
# image are typically rendered as a "broken image" icon by the browser.
# Use cautiously.
#
{ +block-as-image }
#.doubleclick.net
#/Realmedia/ads/
#ar.atwola.com/

# Now you noticed that the default configuration breaks Forbes
# Magazine, but you were too lazy to find out which action is the
# culprit, and you were again too lazy to give feedback, so you just
# used the fragile alias on the site, and -- whoa! -- it worked. The
# 'fragile' aliases disables those actions that are most likely to break
# a site. Also, good for testing purposes to see if it is Privoxy that
# is causing the problem or not.
#
{ fragile }
#.forbes.com

# Here are some sites we wish to support, and we will allow their ads
# through.
#
{ allow-ads }
.adtmag.com
#.sourceforge.net
#.slashdot.org
#.osdn.net

# user.action is generally the best place to define exceptions and
# additions to the default policies of default.action. Some actions are
# safe to have their default policies set here though. So let's set a
# default policy to have a 'blank' image as opposed to the checkerboard
# pattern for ALL sites. '/' of course matches all URLs.
# patterns:
#
{ +set-image-blocker{blank} }
#/

# Enable the following section (not the regression-test directives)
# to rewrite and redirect click-tracking URLs on news.google.com.
# Disabling JavaScript should work as well and probably works more reliably.
#
# Redirected URL = http://news.google.com/news/url?ct2=us%2F0_0_s_1_1_a&sa=t&usg=AFQjCNHJWPc7ffoSXPSqBRz55jDA0KgxOQ&cid=8797762374160&url=http%3A%2F%2Fonline.wsj.com%2Farticle%2FSB10001424052970204485304576640791304008536.html&ei=YcqeTsymCIjxggf8uQE&rt=HOMEPAGE&vm=STANDARD&bvm=section&did=-6537064229385238098
# Redirect Destination = http://online.wsj.com/article/SB10001424052970204485304576640791304008536.html
# Ignore = Yes
#
#{+fast-redirects{check-decoded-url}}
#news.google.com/news/url.*&url=http.*&

# Enable the following section (not the regression-test directives)
# to block various Facebook "like" and similar tracking URLs.  At the
# time this section was added it was reported to not break Facebook
# itself but this may have changed by the time you read this. This URL
# list is probably incomplete and if you don't have an account anyway,
# you may prefer to block the whole domain.
#
# Blocked URL = http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Ffacebook.com%2Farstechnica&width=300&colorscheme=light&show_faces=false&stream=false&header=false&height=62&border_color=%23FFFFFF
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/activity.php?site=arstechnica.com&width=300&height=370&header=false&colorscheme=light&recommendations=false&border_color=%23FFFFFF
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/fan.php?api_key=368513495882&connections=10&height=250&id=8304333127&locale=en_US&sdk=joey&stream=false&width=377
# Ignore = Yes
# Blocked URL = http://www.facebook.com/plugins/like.php?api_key=368513495882&channel_url=http%3A%2F%2Fstatic.ak.fbcdn.net%2Fconnect%2Fxd_proxy.php%3Fversion%3D3%23cb%3Df13997452c%26origin%3Dhttp%253A%252F%252Fonline.wsj.com%252Ff1b037e354%26relation%3Dparent.parent%26transport%3Dpostmessage&extended_social_context=false&href=http%3A%2F%2Fonline.wsj.com%2Farticle%2FSB10001424052970204485304576640791304008536.html&layout=button_count&locale=en_US&node_type=link&ref=wsj_share_FB&sdk=joey&send=false&show_faces=false&width=90
# Ignore = Yes
#
#{+block{Facebook "like" and similar tracking URLs.}}
#www.facebook.com/(extern|plugins)/(login_status|like(box)?|activity|fan)\.php

# Hide cookie and privacy information banner on the Bundeswehr website.
# The relevant parts seem to work without accepting cookies.
# {+filter{bundeswehr.de}}
# .bundeswehr.de/

######### Examples for SSL actions #########
# Following section enables TLS/SSL filtering for all sites defined by pattern and requested by HTTPS.
# {+https-inspection}
# privoxy.org

# Following section turns off certificate verification for all sites defined by pattern.
# {+ignore-certificate-errors}
# privoxy.org
